# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: varint.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvarint.proto\"\x17\n\x06varint\x12\r\n\x05value\x18\x01 \x01(\r\"\x17\n\x06uint32\x12\r\n\x05value\x18\x01 \x01(\r\"\x17\n\x06\x64ouble\x12\r\n\x05value\x18\x01 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'varint_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VARINT']._serialized_start=16
  _globals['_VARINT']._serialized_end=39
  _globals['_UINT32']._serialized_start=41
  _globals['_UINT32']._serialized_end=64
  _globals['_DOUBLE']._serialized_start=66
  _globals['_DOUBLE']._serialized_end=89
# @@protoc_insertion_point(module_scope)
